spring:
  application:
    name: telegram-service
  cloud:
    loadbalancer:
      ribbon:
        enabled: false
  
  datasource:
    url: ${DATABASE_URL:}
    username: avnadmin
    password: ${DATABASE_PASSWORD:}
    driver-class-name: com.mysql.cj.jdbc.Driver

    hikari:
      maximum-pool-size: 5      # Max connections to database
      minimum-idle: 2           # Min connections kept alive
      connection-timeout: 30000 # Wait time for connection (30 sec)
      idle-timeout: 600000      # Remove idle connections after 10 min
      max-lifetime: 1800000     # Recycle connections after 30 min
  
  jpa:
    hibernate:
      ddl-auto: update    # Auto-creates/updates database tables
    show-sql: true        # Shows SQL queries in console (debugging)

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

logging:
  level:
    com.zaxxer.hikari: DEBUG
    org.hibernate.SQL: DEBUG

management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus
  endpoint:
    health:
      show-details: always

server:
  port: 8081